### ISSUE TITLE
关于报错EOFError

### ISSUE THREAD

**Issue by DevKPro** [yisun98/SOLC#7]
在部署环境后，使用train.py脚本进行训练，训练时使用的命令行代码为：
`python train.py --train-batch-size 16 --val-batch-size 16`
出现如下报错信息：
`======> model SOLC Version seven =============== 
Starting Epoch: 0
  0%|                                                                               | 0/1470 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/resource_sharer.py", line 149, in _serve
    send(conn, destination_pid)
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/reduction.py", line 180, in send_handle
    sendfds(s, [handle])
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/reduction.py", line 145, in sendfds
    sock.sendmsg([msg], [(socket.SOL_SOCKET, socket.SCM_RIGHTS, fds)])
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/resource_sharer.py", line 151, in _serve
    close()
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/resource_sharer.py", line 52, in close
    os.close(new_fd)
OSError: [Errno 9] Bad file descriptor
  0%|                                                                               | 0/1470 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 458, in <module>
    trainer.training(epoch)
  File "train.py", line 309, in training
    for index, data in enumerate(tbar):
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/data/anaconda3/envs/lap/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/data/anaconda3/envs/lap/lib/python3.7/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError`
请问这是环境没配置好的原因吗？应该如何解决这个问题？
另外，本人使用的操作系统为ubuntu18，GPU为3090，python版本为3.7。

**Comment by yisun98** [comment]
感谢关注。

个人推测可能是环境问题。因为我这边暂未出现该情况。可以检测训练环境问题，或者数据集的处理部分。特别是后者，可能会出现EOFError.

如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。有问题可随时联系。
